#server:
#  port: 8083
#
#spring:
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
#  h2:
#    console.enabled: true
#
#keycloak:
#  server:
#    contextPath: /auth
#    adminUser:
#      username: admin
#      password: test
#    realmImportFile: syspro-realm.json
