server:
  port: 8083

spring:
  application.name: authorization server keycloak
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id.new_generator_mappings: true
        temp.use_jdbc_metadata_defaults: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/authserverdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 20
      maximum-pool-size: 200
      pool-name: keycloakAuthSvcPool
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: test
    realmImportFile: syspro-realm.json