logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 123456
        tomcat:
            max-active: 50
            max-idle: 20
            max-wait: 20000
            min-idle: 15
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate.ddl-auto: none
        properties:
            hibernate.format_sql.show-sql: true
