spring:
  cache:
    redis:
      cache-null-values: false
      time-to-live: 120000
      use-key-prefix: true
    type: redis
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 12
      minimum-idle: 5
    password: 123456
    url: jdbc:postgresql://localhost:5432/sysperson
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 7.0
        max-idle: 7
        max-wait: -1ms
        min-idle: 2
      shutdown-timeout: 200ms
    password: ''
    port: 6379
